version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "8883:8883"
      - "28083:8883"
      - "8084:8084"
      - "18081:8081"
      - "18083:18083"
    environment:
      TZ: Asia/Shanghai
      EMQX_NAME: emqx
      EMQX_HOST: 0.0.0.0
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  ids:
    image: suposce/ids:latest
    container_name: ids
    network_mode: host
    depends_on:
      - postgres
      - emqx
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: worker
    network_mode: host
    command: celery -A celery_tasks worker --loglevel=info
    depends_on:
      - redis
      - postgres
      - emqx
    restart: unless-stopped

volumes:
  pgdata:

